track_objects:
- person
- cat
confidence_threshold: 0.6
dead_zone: 0.1
pid:
  horizontal:
    kp: 200
    ki: 0.1
    kd: 10
  vertical:
    kp: 200
    ki: 0.1
    kd: 10
fader:
  enable: true
  max_distance: 0.5
  min_factor: 0.1
  max_factor: 1
servo:
  channel_horizontal: 0
  channel_vertical: 15
  freq: 50
  i2c_address: 64
  servo_min_us: 500
  servo_max_us: 2500
  max_angle_horizontal: 270
  max_angle_vertical: 180
camera_movement:
  mode: 0
  enable: false
  horizontal_min_angle: 0
  horizontal_max_angle: 270
  vertical_min_angle: 45
  vertical_max_angle: 135
  scan_speed: 1
  scan_period: 15
window_mover:
  window_name: Hailo Detection App
  move_x: 440
  move_y: 62
  max_retries: 10
  delay: 3
tracking:
  max_age: 30
  min_hits: 3
  iou_threshold: 0.2
  dt: 0.03
  kalman_filter:
    Q:
    - - 1
      - 0
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 1
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 0
      - 1
      - 0
      - 0
      - 0
    - - 0
      - 0
      - 0
      - 1
      - 0
      - 0
    - - 0
      - 0
      - 0
      - 0
      - 1
      - 0
    - - 0
      - 0
      - 0
      - 0
      - 0
      - 1
    R:
    - - 1
      - 0
      - 0
      - 0
    - - 0
      - 1
      - 0
      - 0
    - - 0
      - 0
      - 1
      - 0
    - - 0
      - 0
      - 0
      - 1
